### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by scythargon** [celery/celerymon#28]
I thought you said that it is supported, but: 

```
$ celerymon
Traceback (most recent call last):
  File "/home/argon/.Envs/burgundy/bin/celerymon", line 5, in <module>
    from celerymon.bin.celerymon import main
  File "/home/argon/.Envs/burgundy/lib/python3.6/site-packages/celerymon/bin/celerymon.py", line 94
    except Exception, exc:
                    ^
SyntaxError: invalid syntax
```

**Comment by auvipy** [comment]
it's still not ready for use!!

**Comment by scythargon** [comment]
Got it, thank you:)
Celery lacks good monitoring so badly.

**Comment by auvipy** [comment]
yes! that's why I will take on this!

**Comment by mcepl** [comment]
Well, at least `2to3` claims that only change which is necessary is:
```diff
---
 celerymon/bin/celerymon.py |    5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

--- a/celerymon/bin/celerymon.py
+++ b/celerymon/bin/celerymon.py
@@ -91,9 +91,8 @@ class MonitorCommand(Command):

             try:
                 monitor.start()
-            except Exception, exc:
-                logger.error('celerymon raised exception %r',
-                             exc, exc_info=True)
+            except Exception:
+                logger.exception('celerymon raised exception')
             except KeyboardInterrupt:
                 pass
```
